### ISSUE TITLE
BadSQL is too efficient!

### ISSUE THREAD

**Issue by emlynlj** [nayakrujul/badsql#1]
BadSQL is too efficient! What do I do?

**Comment by nayakrujul** [comment]
Thanks for the compliment!

Feel free to use time.sleep(random.random()) to slow your program down!

Thanks!

**Comment by nayakrujul** [comment]
Hi @emlynlj 

You can now use `pip install badsql` in the terminal and use it directly in your program with `from badsql import db, load` as it is now on PyPI! You can read the docs [here](https://github.com/nayakrujul/badsql/blob/main/README.md).

Thanks
